# Generated by Django 4.1 on 2022-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_watchlistmovie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistmovie',
            name='release_date',
            field=models.TextField(),
        ),
    ]
